DATA:
  data_root: /data/cityscapes
  train_list: /data/cityscapes/list/fine_train.txt
  val_list: /data/cityscapes/list/fine_val.txt
  classes: 19

TRAIN:
  arch: psp
  layers: 50
  sync_bn: True  # adopt syncbn or not
  train_h: 713
  train_w: 713
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 200
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 1
  print_freq: 50
  save_freq: 1
  save_path: /logs/exp/cityscapes/pspnet50_0.5/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  sparsity: 0.5
  starting_epoch: 0
  ending_epoch: 50
Distributed:
  dist_url: tcp://127.0.0.1:5002
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_list: /data/cityscapes/list/fine_val.txt
  split: val # split in [train, val and test]
  base_size: 2048  # based size for scaling
  test_h: 713
  test_w: 713
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: true # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  model_path: /checkpoints/pspnet50_0.5.pth  # evaluation model path
  save_folder: /logs/exp/cityscapes/pspnet50_0.5/result/epoch_200/val/ss  # results save folder
  colors_path: /code/semseg/data/cityscapes/cityscapes_colors.txt  # path of dataset colors
  names_path: /code/semseg/data/cityscapes/cityscapes_names.txt  # path of dataset category names
  sparse: true
  calc_results: true
  result_path: /logs/exp/evals/cityscapes_pspnet50_0.5.csv # evaluation result path
  demo_save_path: /code/semseg/figure/val/pspnet50_0.5 # evaluation result path
